services:
  - type: web
    name: campus-marketplace
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn campus_marketplace.wsgi:application -c gunicorn.conf.py"
    plan: free
    healthCheckPath: /health/
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_S3_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_SECRET_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET_NAME
        value: listing_images
      - key: SUPABASE_S3_ENDPOINT_URL
        value: https://xlcmrhqhvulypglyxtov.supabase.co/storage/v1/s3
      - key: SUPABASE_S3_REGION_NAME
        value: ap-southeast-2
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
