# Generated by Django 6.1.1 on 2026-10-07 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('TEXTBOOKS', 'Textbooks'), ('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('HOUSING', 'Housing'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload a clear photo of the item', null=True, upload_to='listings/')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_0bc035_idx'), models.Index(fields=['category'], name='marketplace_categor_c8d31d_idx')],
            },
        ),
    ]
