# Generated by Django 6.1.1 on 2026-10-07 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_campus_pickup_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='pickup_location',
            field=models.CharField(choices=[('STUDENT_UNION', 'Student Union'), ('CENTRAL_LIBRARY', 'Central Library'), ('NORTH_QUAD_DORMS', 'North Quad Dorms'), ('SCIENCE_BLOCK', 'Science Block'), ('SPORTS_COMPLEX', 'Sports Complex'), ('MAIN_GATE', 'Main Campus Gate')], default='STUDENT_UNION', help_text='Designated safe campus meetup spot', max_length=40),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['pickup_location'], name='marketplace_pickup__5b4eed_idx'),
        ),
        migrations.AddField(
            model_name='listingmessage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='marketplace.listing'),
        ),
        migrations.AddField(
            model_name='listingmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listingmessage',
            index=models.Index(fields=['listing', 'sender', 'receiver'], name='marketplace_listing_38ac9a_idx'),
        ),
        migrations.AddIndex(
            model_name='listingmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='marketplace_receive_86483a_idx'),
        ),
    ]
