# Generated by Django 6.1.1 on 2026-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listingmessage_listing_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TEXTBOOKS', 'Textbooks & Study Material'), ('ELECTRONICS', 'Electronics & Gadgets'), ('DORM_LIVING', 'Hostel & Dorm Essentials'), ('STATIONERY', 'Stationery & Lab Equipment'), ('FASHION', 'Clothing & Formal Wear'), ('BICYCLES_COMMUTE', 'Bicycles & Campus Commute'), ('SPORTS_FITNESS', 'Sports & Gym Gear'), ('ENTERTAINMENT', 'Gaming, Hobbies & Instruments'), ('LOST_AND_FOUND', 'Lost & Found'), ('OTHER', 'Miscellaneous')], db_index=True, default='TEXTBOOKS', max_length=32),
        ),
    ]
