# Generated by Django 6.1.1 on 2026-10-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerificationOTP',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
