# Generated by Django 6.1.1 on 2026-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_restore_otp_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Designates whether this student has verified account credentials.'),
        ),
        migrations.DeleteModel(
            name='EmailVerificationOTP',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
